version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-php
    volumes:
      - ../:/var/www/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OPCACHE_VALIDATE_TIMESTAMPS: '0'
      PHP_OPCACHE_MAX_ACCELERATED_FILES: '7963'
      PHP_OPCACHE_MEMORY_CONSUMPTION: '192'
      PHP_OPCACHE_MAX_WASTED_PERCENTAGE: '10'
    depends_on:
      - postgresql
      - redis
    networks:
      - nginx-php-postgres-redis

  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ../:/var/www
    depends_on:
      - php
    networks:
      - nginx-php-postgres-redis

  postgresql:
    image: postgres:14-alpine
    container_name: my-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres/data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - nginx-php-postgres-redis

  redis:
    image: redis:alpine
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - nginx-php-postgres-redis

networks:
  nginx-php-postgres-redis:
    driver: bridge
