version: '3.9'

services:
  php:
    build: .
    container_name: my-php
    volumes:
      - ../:/var/www/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis
    restart: on-failure
    networks:
      - nginx-php-postgres-redis

  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ../:/var/www
    depends_on:
      - php
    networks:
      - nginx-php-postgres-redis

  postgres:
    image: postgres:14
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /data/postgres
    volumes:
      - ./postgres/data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - nginx-php-postgres-redis

  pgadmin:
    container_name: my-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./postgres/pgadmin:/var/lib/pgadmin
    ports:
      - "8003:80"
    networks:
      - nginx-php-postgres-redis

  redis:
    image: redis:alpine
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - nginx-php-postgres-redis

networks:
  nginx-php-postgres-redis:
    driver: bridge
